_wandb:
    value:
        cli_version: 0.22.2
        e:
            rarhdi4zuw8ol9od0mywrbhmxjsdisxa:
                args:
                    - --gesture_threshold=0.4366327187115633
                    - --min_gap_s=0.7536168837814327
                    - --min_length_s=0.499493722608796
                    - --motion_threshold=0.16196488072282353
                codePath: EnvisionParam/evaluate.py
                codePathLocal: evaluate.py
                email: autoshin0322@gmail.com
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/envision/bin/python
                git:
                    commit: 50f8f0ffce056754940daec38dc57c35c6995ba5
                    remote: git@github.com:autoshin0322/Jayproject.git
                host: Jaes-MacBook-Pro.local
                os: macOS-14.3-arm64-arm-64bit
                program: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam/evaluate.py
                python: CPython 3.10.0
                root: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam
                startedAt: "2025-10-27T01:00:21.846299Z"
                writerId: rarhdi4zuw8ol9od0mywrbhmxjsdisxa
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 53
            "2":
                - 2
                - 3
                - 5
                - 8
                - 12
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.0
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
gesture_threshold:
    value: 0.4366327187115633
min_gap_s:
    value: 0.7536168837814327
min_length_s:
    value: 0.499493722608796
motion_threshold:
    value: 0.16196488072282353
