_wandb:
    value:
        cli_version: 0.22.2
        e:
            hzaocqgah6acwb0v587iyso5h1oxppi9:
                args:
                    - --gesture_threshold=0.3861523073712078
                    - --min_gap_s=0.3169373478400783
                    - --min_length_s=0.6353764370991936
                    - --motion_threshold=0.7610168872013888
                codePath: EnvisionParam/evaluate.py
                codePathLocal: evaluate.py
                email: autoshin0322@gmail.com
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/envision/bin/python
                git:
                    commit: 50f8f0ffce056754940daec38dc57c35c6995ba5
                    remote: git@github.com:autoshin0322/Jayproject.git
                host: Jaes-MacBook-Pro.local
                os: macOS-14.3-arm64-arm-64bit
                program: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam/evaluate.py
                python: CPython 3.10.0
                root: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam
                startedAt: "2025-10-27T00:58:52.069409Z"
                writerId: hzaocqgah6acwb0v587iyso5h1oxppi9
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 53
            "2":
                - 2
                - 3
                - 5
                - 8
                - 12
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.0
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
gesture_threshold:
    value: 0.3861523073712078
min_gap_s:
    value: 0.3169373478400783
min_length_s:
    value: 0.6353764370991936
motion_threshold:
    value: 0.7610168872013888
