_wandb:
    value:
        cli_version: 0.22.2
        e:
            r57m327rfg0r6ufne11686wm81mjqrk8:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "8589934592"
                args:
                    - --gesture_threshold=0.5313372519438161
                    - --min_gap_s=0.3587361746813754
                    - --min_length_s=0.9479157894081924
                    - --motion_threshold=0.30848094505230184
                codePath: EnvisionParam/run_detect.py
                codePathLocal: run_detect.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "398802874368"
                email: autoshin0322@gmail.com
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/envision/bin/python
                git:
                    commit: 50f8f0ffce056754940daec38dc57c35c6995ba5
                    remote: git@github.com:autoshin0322/Jayproject.git
                host: Jaes-MBP
                memory:
                    total: "17179869184"
                os: macOS-14.3-arm64-arm-64bit
                program: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam/run_detect.py
                python: CPython 3.10.0
                root: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam
                startedAt: "2025-10-27T05:00:10.325562Z"
                writerId: r57m327rfg0r6ufne11686wm81mjqrk8
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 53
            "2":
                - 2
                - 3
                - 5
                - 8
                - 12
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.0
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
gesture_threshold:
    value: 0.5313372519438161
min_gap_s:
    value: 0.3587361746813754
min_length_s:
    value: 0.9479157894081924
motion_threshold:
    value: 0.30848094505230184
