_wandb:
    value:
        cli_version: 0.22.2
        e:
            amuulqtb4l13hr7uwr27jl9w815zbsra:
                codePath: EnvisionParam/evaluate.py
                codePathLocal: evaluate.py
                email: autoshin0322@gmail.com
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/envision/bin/python
                git:
                    commit: 50f8f0ffce056754940daec38dc57c35c6995ba5
                    remote: git@github.com:autoshin0322/Jayproject.git
                host: Jaes-MacBook-Pro.local
                os: macOS-14.3-arm64-arm-64bit
                program: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam/evaluate.py
                python: CPython 3.10.0
                root: /Users/jaehyunshin/Desktop/Jayproject/EnvisionParam
                startedAt: "2025-10-27T00:24:21.589485Z"
                writerId: amuulqtb4l13hr7uwr27jl9w815zbsra
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 53
            "2":
                - 2
                - 3
                - 5
                - 12
                - 53
            "3":
                - 2
            "4": 3.10.0
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
